[package]
name = "interactive"
version = "1.0.3"
authors = ["Joe Frikker <jfrikker@gmail.com>"]

[profile.release]
panic = "abort"
lto = true

[dependencies]
dirs = "1.0"
itertools = "0.8"
linefeed = "0.5"
nix = "0.13.0"
quick-error = "1.2"
try_map = "0.3"